# Generated by Django 5.0.2 on 2026-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_user_category_hazardreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Resolved', 'resolved')], default='active', max_length=20),
        ),
    ]
