# Generated by Django 5.0.2 on 2026-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_hazardreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardreport',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Resolved', 'resolved')], default='Active', max_length=20),
        ),
    ]
