# Generated by Django 5.0.2 on 2026-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_hazardreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardreport',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
