# Generated by Django 5.0.2 on 2026-05-11 20:06

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models


def split_shared_hazards(apps, schema_editor):
    Patient = apps.get_model('Core', 'Patient')
    HazardReport = apps.get_model('Core', 'HazardReport')
    db_alias = schema_editor.connection.alias

    patients_by_hazard = defaultdict(list)
    for patient in Patient.objects.using(db_alias).order_by('id'):
        patients_by_hazard[patient.hazard_id].append(patient.id)

    for hazard_id, patient_ids in patients_by_hazard.items():
        if len(patient_ids) <= 1:
            continue

        original_hazard = HazardReport.objects.using(db_alias).get(pk=hazard_id)

        for patient_id in patient_ids[1:]:
            cloned_hazard = HazardReport.objects.using(db_alias).create(
                user_id=original_hazard.user_id,
                title=original_hazard.title,
                description=original_hazard.description,
                servity=original_hazard.servity,
                status=original_hazard.status,
            )
            Patient.objects.using(db_alias).filter(pk=patient_id).update(hazard_id=cloned_hazard.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_patient_patient_id'),
    ]

    operations = [
        migrations.RunPython(split_shared_hazards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patient',
            name='hazard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.hazardreport'),
        ),
    ]
