# Generated by Django 5.0.2 on 2026-05-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_patient_hazard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hazard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Core.hazardreport'),
        ),
    ]
