# Generated by Django 5.0.2 on 2026-05-11 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_patient_hazard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('last_seen_location', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('missing_person_name', models.CharField(max_length=100)),
                ('missing_person_age', models.IntegerField()),
                ('missing_person_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='missing_people/')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_complaints', to='Core.hazardreport')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_complaints', to='Core.patient')),
            ],
        ),
    ]
