# Generated by Django 5.0.2 on 2026-05-11 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_missingcomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingcomplaint',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_complaints', to='Core.patient'),
        ),
    ]
